In [2]:

# 1）使用pytorch创建一个tensor
# 2）tensor的基本操作

In [3]:
import torch
import numpy as np

In [32]:

# 一个tensor可以有不用的维度，可以是1维的，2维的，也可以是3维，4维的，我们先来创建一个空的tensor

x = torch.empty(1)
y = torch.empty(2)
x,y

# 括号里面我们要给tensor一个size，空的tensor不代表是空的张量，可以看到x只有一个元素，y里面有3个元素，y可以理解维1维的向量包含2个元素


(tensor([0.]), tensor([0., 0.]))

In [28]:
# 现在我们创建一个2维的tensor

x = torch.empty(2,1)
y = torch.empty(3,2)
x,y
# 他看起来像一个二维的矩阵，也有些像三行两列的矩阵

(tensor([[0.],
         [0.]]),
 tensor([[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 7.8473e-44]]))

In [29]:
# 现在我们创建一个3维的tensor

x = torch.empty(2,1,3)
y = torch.empty(3,2,1)
x,y
# 他看起来像一个二维的矩阵，也有些像三行两列的矩阵

(tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00]],
 
         [[0.0000e+00, 0.0000e+00, 7.8473e-44]]]),
 tensor([[[0.0000e+00],
          [8.1275e-44]],
 
         [[2.7003e-06],
          [2.6705e-06]],
 
         [[8.4488e+20],
          [4.2724e-05]]]))

In [41]:
# 我们也可以用随机值来生成tesor，或者生成一个全为0/1的tensor
 

x = torch.rand(2,1)
y = torch.zeros(3,2)
z  = torch.ones(3,2)
x,y,z


(tensor([[0.2676],
         [0.3381]]),
 tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [43]:
# 我们也可以指定我们的数据的类型，先来看一下默认的数据类型

x = torch.rand(2,1)
x.dtype

torch.float32

In [5]:
# 我们也可以指定我们的数据的类型 eg.double,folat16

x = torch.rand(2,1,dtype=torch.float64)
x.dtype

torch.float64

In [7]:
# 我们也可以查看我们的数据的size,因为size是一个函数，所以产看size的时候需要加括号

x = torch.rand(2,1,dtype=torch.float64)
x.size()

torch.Size([2, 1])

In [9]:
# 我们也可以将从其他的python的数据类型eg我们的列表或者array转化成我们的tensor
x = torch.tensor([2,1,9])
x

tensor([2, 1, 9])

In [19]:
# 接下来我们来看我们的tesor的基本的运算，比如说我们的加减乘除
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x+y
z1 = torch.add(x,y)
x,y,z,z1


(tensor([[0.3290, 0.4252],
         [0.7578, 0.1285]]),
 tensor([[0.8928, 0.0837],
         [0.1531, 0.2310]]),
 tensor([[1.2219, 0.5089],
         [0.9109, 0.3595]]),
 tensor([[1.2219, 0.5089],
         [0.9109, 0.3595]]))

In [24]:
# 注意如果我们使用以下这种方式，那么我的变量y会变成 x+y，在pytorch中，如果在一个函数后面加一个下划线的话，那个就相当于使用 = 
y.add_(x)
y

tensor([[2.2090, 1.7847],
        [3.1843, 0.7452]])

In [26]:
# 当然减法也可以使用这种方式

x = torch.rand(2,2)
y = torch.rand(2,2)
z = x-y
z1 = torch.sub(x,y)
x,y,z,z1


(tensor([[0.4969, 0.4190],
         [0.6998, 0.3150]]),
 tensor([[0.3287, 0.3284],
         [0.7985, 0.3828]]),
 tensor([[ 0.1682,  0.0905],
         [-0.0987, -0.0678]]),
 tensor([[ 0.1682,  0.0905],
         [-0.0987, -0.0678]]))

In [27]:
# 当然乘法也可以使用这种方式

x = torch.rand(2,2)
y = torch.rand(2,2)
z = x*y
z1 = torch.mul(x,y)
x,y,z,z1


(tensor([[0.7932, 0.1408],
         [0.1936, 0.6415]]),
 tensor([[0.3042, 0.2218],
         [0.5851, 0.5936]]),
 tensor([[0.2413, 0.0312],
         [0.1133, 0.3808]]),
 tensor([[0.2413, 0.0312],
         [0.1133, 0.3808]]))

In [28]:
# 当然乘法也可以使用这种方式

x = torch.rand(2,2)
y = torch.rand(2,2)
z = x/y
z1 = torch.div(x,y)
x,y,z,z1


(tensor([[0.7676, 0.8390],
         [0.7951, 0.0676]]),
 tensor([[0.1735, 0.9877],
         [0.4220, 0.3648]]),
 tensor([[4.4247, 0.8495],
         [1.8844, 0.1853]]),
 tensor([[4.4247, 0.8495],
         [1.8844, 0.1853]]))

In [29]:
# 以上就是我们的tensor的基础运算

In [37]:
# 接下来我们可以像numpy或者df一样对我们的tesor进行切片

x = torch.rand(5,3)
# 这里比如说我们取所有的行第一列的数据，或者第一行，或者取一个元素
x,x[:,1]




(tensor([[0.9377, 0.9684, 0.5864],
         [0.1396, 0.1496, 0.5913],
         [0.2814, 0.8852, 0.0992],
         [0.1747, 0.1173, 0.7173],
         [0.1256, 0.9443, 0.9350]]),
 tensor([0.9684, 0.1496, 0.8852, 0.1173, 0.9443]))

In [54]:
# 我们可以对我们的tensor进行reshape，但是注意reshape的时候元素的个数是一样的
x = torch.rand(4,4)
y = x.view(16)
x,y
# 现在可以看到我们的y只有1维的tensor 
# 如果我们不想输入是size的第一个值，也就是维度，我们可以用-1来代替，他会自动的帮我们算出来

z = x.view(-1,8)
z.size()



torch.Size([2, 8])

In [72]:
# 现在我们来讨论一下numpy和tensor的互相转换,我们先来创建一个tensor
a = torch.ones(5)
b = a.numpy()
a,b



(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [67]:
# 这里如果你的tensor和numpy都是在cup上存储时，那么这个变量a和b是在内存中使用同一个地址的，如果说你修改了一个，那么另一个也是会修改掉的，eg
a.add_(1)
a,b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [71]:
# 接下来我们来创建一个numpy
a = np.ones(5)
b = torch.from_numpy(a)
a,b

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [73]:
# 同理如果你修改了a的值，b的值也会被修改
a += 1
a,b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [77]:
# 如果你的gpu是可用的，tensor是存放在gpu上的，可以使用下面的代码在gpu上创建tensor
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
# 一般来说在gpu上的计算速度会比在cpu上的速度快很多，这里注意tensor是可以放在gpu的，而我们的numpy是只能存储在cpu的，所以如果要将z转换成numpy，需要将tensor先放到我们的cpu上。
    z = z.to("cpu")
    z.numpy()


In [79]:
# 如果你有一个参数要优化，需要用到梯度下降法，当我们在创建一个tensor的时候，我们可以直接输入~为true，这样他会自动的帮我们计算梯度

x = torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)